## Notebook for pytorch foundation exercises
https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

1. Create a random tensor with shape `(7, 7)`

In [1]:
import torch

X = torch.rand(7, 7)
X.shape

torch.Size([7, 7])

2. Perform a matrix multiplication on the tensor from 1 with another random tensor with shape `(1, 7)`

In [3]:
Y = torch.rand(1, 7)
Y @ X

tensor([[0.8966, 2.5625, 1.8968, 1.7336, 1.2835, 1.4096, 2.1108]])

3. Set the random seed to 0 and do exercises 1 & 2 over again

In [4]:
SEED = 0
torch.manual_seed(SEED)
X = torch.rand(7, 7)
Y = torch.rand(1, 7)
Y @ X

tensor([[2.1581, 1.9307, 2.8454, 2.6230, 1.9117, 2.0266, 1.4257]])

4. Set the GPU random seed to `1234`

In [6]:
torch.cuda.manual_seed(1234)

5. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors

In [7]:
X = torch.rand(2, 3, device=torch.device('cuda:0'))
Y = torch.rand(2, 3, device=torch.device('cuda:0'))

6. Perform a matrix multiplication on the tensors you created in 5

In [9]:
R = X @ Y.T

7. Find the maximum and minimum values of the output of 6.

In [11]:
print(R.max(), R.min())

tensor(0.7668, device='cuda:0') tensor(0.2786, device='cuda:0')


8. Find the maximum and minimum index values of the output of 6.

In [12]:
print(R.argmax(), R.argmin())

tensor(1, device='cuda:0') tensor(0, device='cuda:0')


9. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape `(10)`. Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.


In [13]:
torch.manual_seed(7)

X = torch.rand(1, 1, 1, 10)
Y = X.squeeze()
print(X, X.shape)
print(Y, Y.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
